Support for custom objectId, implements #1087
parse-community/Parse-SDK-Android pull request #1088
Opened 2021-04-12 10:31 UTC by martinpfannemueller

I implemented the custom objectId feature mentioned in #1087 including unit tests. Is there something missing to get this merged?

Thanks!

2021-10-14 19:42 UTC, martinpfannemueller commented
I just merged the changes from the master. Again, locally everything runs just fine.

2021-10-15 19:07 UTC, martinpfannemueller commented
Still the same problem. This maybe has to do something with the OS or the development environment then. I am running the tests inside Android Studio on macOS. In general, do you have an idea how we can debug the two failing tests in the CI pipeline?

2021-10-15 21:05 UTC, martinpfannemueller commented
I just tried to update the unit tests as it was partly possible to reproduce the failing tests. It definitely has something to do with the Parse instance. Therefore, I tried to clean them up properly now in the new tests at the end.

2021-10-21 00:32 UTC, mtrezza commented
> It would definitely help if you could provide some guidelines how the mocking and the different plugins as well as the different states of the mocked objects work together in the tests, e.g., by providing a sample when using the local datastore or when a specific response is expected.

@L3K0V @Jawnnypoo could you do that or should I look into it?

2021-10-21 14:03 UTC, Jawnnypoo commented
I don't have context into that, sorry.

2021-11-03 08:40 UTC, L3K0V approved these changes
@mtrezza @martinpfannemueller LGTM

2021-11-03 14:13 UTC, mtrezza requested changes
Could you please also add doc headers to the new public properties and methods?

2021-11-16 07:45 UTC, L3K0V commented
@martinpfannemueller gentle ping when you have some free time if is possible to add some JavaDoc as @mtrezza pleases, so this can be merged. Looking forward to see this merged 🤞

2021-11-21 10:15 UTC, martinpfannemueller commented
I just added some JavaDoc to allowCustomObjectId() in the configuration builder and the isAllowCustomObjectId() getter.

2021-11-21 13:47 UTC, mtrezza commented on parse/src/main/java/com/parse/Parse.java
> +             * Enable the possibility to set a custom objectId for your ParseObjects.
Could you shorten this to:

> Allow to set a custom objectId for ParseObjects.

2021-11-21 13:48 UTC, mtrezza commented
There also seems to be a lint fix needed.

2021-11-21 15:30 UTC, martinpfannemueller commented
I updated the JavaDoc and ran spotlessApply

2021-11-21 16:12 UTC, mtrezza commented
Thanks, let just see whether the CI passes.

2021-11-21 16:15 UTC, mtrezza approved these changes
Looks good, thanks for this PR!

2021-11-21 16:15 UTC, merged

2021-11-21 16:17 UTC, parseplatformorg commented
🎉 This change has been released in version [2.1.0](https://github.com/parse-community/Parse-SDK-Android/releases/tag/2.1.0)