Bugfix: fixes #1155 - supporting concurrent download of the same ParseFile from multiple threads
parse-community/Parse-SDK-Android pull request #1179
Opened 2022-08-21 13:19 UTC by techyourchance

### New Pull Request Checklist

- [ x ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Android/blob/master/SECURITY.md).
- [ x ] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Android/issues?q=is%3Aissue).

### Issue Description

Related issue: #`1155`

### Approach

This PR simplifies the logic of `fetchAsync` method and then adds a concurrent code that blocks the second (and further) calling threads until the first thread finishes the download of ParseFile (or fails to do so).

### TODOs before merging

- [ x ] Add tests
- [ x ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

2022-08-22 17:44 UTC, mtrezza requested changes
Just removing some empty lines...

2022-08-22 17:44 UTC, mtrezza commented on parse/src/test/java/com/parse/ParseFileControllerTest.java
> +        assertFalse(controller.getTempFile(state).exists());
```suggestion
        countDownLatch.await();

        File result1 = file1Ref.get();
        File result2 = file2Ref.get();
        
        assertTrue(result1.exists());
        assertEquals("hello", ParseFileUtils.readFileToString(result1, "UTF-8"));
        assertTrue(result2.exists());
        assertEquals("hello", ParseFileUtils.readFileToString(result2, "UTF-8"));
        verify(fileClient, times(1)).execute(any(ParseHttpRequest.class));
        assertFalse(controller.getTempFile(state).exists());
```

2022-08-22 17:44 UTC, mtrezza commented on parse/src/test/java/com/parse/ParseFileControllerTest.java
> +        CountDownLatch countDownLatch = new CountDownLatch(2);
```suggestion
        ParseFileController controller = new ParseFileController(null, root).fileClient(fileClient);
        ParseFile.State state = new ParseFile.State.Builder().name("file_name").url("url").build();
        CountDownLatch countDownLatch = new CountDownLatch(2);
```

2022-08-22 17:49 UTC, mtrezza requested changes
Thanks for the fix! Could you take a look at the failing lint test?

2022-08-23 08:35 UTC, rommansabbir commented
> Thanks for the fix! Could you take a look at the failing lint test?

I will take a look at the fail and it seems like `Spotless` not applied.

2022-08-23 13:30 UTC, rommansabbir commented
@techyourchance @mtrezza Closing this PR as created a new PR (#1180) by fixing the CI failing issue for Spotless violations.

2022-08-23 13:30 UTC, closed without merging